name: Draft a release note

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: release-drafter/release-drafter@0931ec6394959eb749e2e4a38a8c46e8e2e3a2d4 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
